// DesireeIA
// Copyright (c) Passaro Francesco Paolo. All rights reserved.
// Licensed under the DesireeIA License - see LICENSE and the "License"
// section of README.md for full terms: no modification, no unauthorized
// integration, no AI training/ingestion without explicit written consent
// from the author.

using System.Text;
using System.Text.Json;

namespace DesireeIA;

/// <summary>
/// Options for streaming generation (<see cref="LocalModel.StreamAsync"/>
/// / <see cref="LocalModel.ChatStreamAsync"/>).
/// </summary>
public sealed class GenerateOptions
{
    /// <summary>Cap on generated tokens beyond which generation stops regardless.</summary>
    public int MaxTokens { get; init; } = 512;

    /// <summary>
    /// If any of these strings appears in the generated text, generation
    /// stops and the returned text does NOT include the stop string
    /// (consistent with the "stop" convention of APIs like Ollama/OpenAI).
    /// </summary>
    public IReadOnlyList<string>? StopSequences { get; init; }
}

/// <summary>
/// Incrementally detects, piece of text after piece of text, whether a stop
/// sequence has appeared. Needed because streaming produces text one token
/// (or token fragment) at a time, but a stop sequence can span multiple
/// consecutive pieces: a small tail of not-yet-emitted text must be held
/// back until it's certain it isn't part of a match.
/// </summary>
public sealed class StopSequenceScanner
{
    private readonly string[] _stops;
    private readonly int _maxStopLen;
    private readonly StringBuilder _tail = new();

    public StopSequenceScanner(IReadOnlyList<string>? stopSequences)
    {
        _stops = (stopSequences ?? Array.Empty<string>())
            .Where(s => !string.IsNullOrEmpty(s))
            .ToArray();
        _maxStopLen = _stops.Length == 0 ? 0 : _stops.Max(s => s.Length);
    }

    public bool HasStops => _stops.Length > 0;

    /// <summary>
    /// Accepts the next decoded piece of text. Returns the text that is now
    /// safe to emit (may be empty) and whether a stop sequence was found (in
    /// which case the caller must stop generation: `emit` is all and only
    /// the text BEFORE the stop sequence).
    /// </summary>
    public (string emit, bool stopped) Feed(string piece)
    {
        if (_stops.Length == 0) return (piece, false);

        _tail.Append(piece);
        var combined = _tail.ToString();

        foreach (var stop in _stops)
        {
            var idx = combined.IndexOf(stop, StringComparison.Ordinal);
            if (idx >= 0)
            {
                var before = combined[..idx];
                _tail.Clear();
                return (before, true);
            }
        }

        // No match yet: everything can be emitted except for a tail as long
        // as the longest stop sequence minus 1 character, because that tail
        // could be the start of a match that completes with the next piece.
        var safeLen = Math.Max(0, combined.Length - (_maxStopLen - 1));
        var toEmit = combined[..safeLen];
        _tail.Clear();
        _tail.Append(combined[safeLen..]);
        return (toEmit, false);
    }

    /// <summary>
    /// Call this when generation ends normally (EOS or token limit) without
    /// ever finding a stop sequence: the text left in the tail isn't part of
    /// one, so it must still be emitted.
    /// </summary>
    public string Flush()
    {
        var s = _tail.ToString();
        _tail.Clear();
        return s;
    }
}

/// <summary>Description of a tool the model can invoke (name, purpose, JSON schema of the parameters).</summary>
public sealed record ToolDefinition(string Name, string Description, string ParametersJsonSchema);

/// <summary>A tool call request extracted from the text generated by the model.</summary>
public sealed record ToolCall(string Name, string ArgumentsJson);

/// <summary>
/// "Prompt-based" tool calling: DesireeIA has no native function-calling
/// format trained into the model (unlike specific "instruct-tools" models),
/// so here the model is asked, via system instructions, to respond with a
/// recognizable JSON block when it wants to invoke a tool, and that block is
/// then parsed. Works well with generic chat models as long as they follow
/// the instruction; not as reliable as grammar-constrained decoding (not
/// implemented).
/// </summary>
public static class ToolCalling
{
    private const string OpenTag = "<tool_call>";
    private const string CloseTag = "</tool_call>";

    /// <summary>
    /// System instruction describing the available tools and the expected
    /// format for invoking them. Meant to be prepended (or appended) to the
    /// conversation's system message.
    /// </summary>
    public static string BuildSystemPrompt(IEnumerable<ToolDefinition> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine("You can call tools to help answer the user. To call a tool, respond with ONLY this block and nothing else (no other text before or after):");
        sb.Append(OpenTag).AppendLine();
        sb.AppendLine("{\"name\": \"<tool name>\", \"arguments\": { ... }}");
        sb.Append(CloseTag).AppendLine();
        sb.AppendLine("If no tool call is needed, answer normally in plain text instead. Available tools:");
        foreach (var t in tools)
        {
            sb.AppendLine($"- {t.Name}: {t.Description}");
            sb.AppendLine($"  parameters (JSON schema): {t.ParametersJsonSchema}");
        }
        return sb.ToString();
    }

    /// <summary>
    /// Looks for a &lt;tool_call&gt;...&lt;/tool_call&gt; block in the generated
    /// text and parses it. Returns false if there is no such block or if the
    /// content isn't valid JSON with a non-empty "name" field.
    /// </summary>
    public static bool TryParse(string responseText, out ToolCall? call)
    {
        call = null;
        if (string.IsNullOrEmpty(responseText)) return false;

        var start = responseText.IndexOf(OpenTag, StringComparison.Ordinal);
        if (start < 0) return false;
        start += OpenTag.Length;
        var end = responseText.IndexOf(CloseTag, start, StringComparison.Ordinal);
        var json = (end < 0 ? responseText[start..] : responseText[start..end]).Trim();
        if (json.Length == 0) return false;

        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;
            if (!root.TryGetProperty("name", out var nameEl)) return false;
            var name = nameEl.GetString();
            if (string.IsNullOrEmpty(name)) return false;
            var argsJson = root.TryGetProperty("arguments", out var argsEl) ? argsEl.GetRawText() : "{}";
            call = new ToolCall(name, argsJson);
            return true;
        }
        catch (JsonException)
        {
            return false;
        }
    }

    /// <summary>
    /// Formats a tool result as a message to append back to the history for
    /// the next turn. Uses the "user" role (not "tool"): DesireeIA's
    /// per-architecture chat templates (see core/chat_template.cpp)
    /// recognize only system/user/assistant for most non-ChatML formats, so
    /// a "tool" role would be silently dropped on those models. "user" with
    /// an explicit prefix works on every template.
    /// </summary>
    public static (string Role, string Content) BuildResultMessage(string toolName, string resultJson)
        => ("user", $"[tool_result name=\"{toolName}\"] {resultJson}");
}

/// <summary>
/// "Best-effort" structured output: since there is no grammar-based decoder
/// (GBNF/JSON-schema constrained sampling) in the native engine, JSON mode
/// here is implemented with a prompt instruction plus a lenient extractor
/// that recovers the first balanced, syntactically valid JSON block even if
/// the model added text or a code fence around it.
/// Does not give hard guarantees like a grammar sampler: if that level of
/// reliability is needed, it must be implemented in the engine (see TODO in
/// docs).
/// </summary>
public static class StructuredOutput
{
    public static string BuildJsonInstruction(string? jsonSchema = null)
    {
        var instr = "Respond with ONLY valid JSON and no other text: no markdown code fences, no explanation before or after.";
        if (!string.IsNullOrWhiteSpace(jsonSchema))
        {
            instr += " The JSON must conform to this schema:\n" + jsonSchema;
        }
        return instr;
    }

    /// <summary>
    /// Looks in the text for the first balanced, syntactically valid JSON
    /// sub-block (object or array), ignoring any surrounding text/markdown.
    /// Returns null if no block parses correctly.
    /// </summary>
    public static string? TryExtractJson(string text)
    {
        for (int i = 0; i < text.Length; i++)
        {
            if (text[i] != '{' && text[i] != '[') continue;
            var open = text[i];
            var close = open == '{' ? '}' : ']';
            var depth = 0;
            var inString = false;
            var escape = false;

            for (int j = i; j < text.Length; j++)
            {
                var c = text[j];
                if (inString)
                {
                    if (escape) escape = false;
                    else if (c == '\\') escape = true;
                    else if (c == '"') inString = false;
                    continue;
                }
                if (c == '"') { inString = true; continue; }
                if (c == open) depth++;
                else if (c == close)
                {
                    depth--;
                    if (depth == 0)
                    {
                        var candidate = text[i..(j + 1)];
                        try
                        {
                            using var _ = JsonDocument.Parse(candidate);
                            return candidate;
                        }
                        catch (JsonException)
                        {
                            break; // this starting point isn't valid JSON, try the next '{'/'['
                        }
                    }
                }
            }
        }
        return null;
    }
}
